### ISSUE TITLE
[REPO] add logging with configurable tagging and color that integrates with hc-core logging

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#29]
As a lib3h client, I can use a logger with configurable tagging and color so that I can efficiently debug network activity (and integrate my own logging with network logging)

Another wording:

As a developer, I wand to see networking related logging so that I can receive feedback on the state of the system.

- [x] - Simple macros so adding logging to modules is trivial
- [ ] - Configurable output channel (allow stdout / stderr / file)
- [x] - Configurable output filter (supports filter / coloring functionality currently in use by holochain-rust)

- [x] SPIKE: Given net crate’s tweetlog && core context’s logger, what is something that solves requirements && hopefully is fairly idiomatic to rust
- [x] RFC comprehensive logger solution to both core and networking teams
- [ ] Implement RFC logger solution

**Comment by dymayday** [comment]
This PR #34  addresses this issue

**Comment by ddd-mtl** [comment]
Maybe use a HackMD to spec this out?
The things I would like:
 - Multiple output channels at a time with different filters.
 - Seperating logLevels from tagging because logLevel should be something understandable by the compiler so it can strip out trace and debug logs when in production.
 - Possibility to add custom suffixs with runtime data to log outputs. (i.e. Adding PID to log output so we can discern instances in multinode scenarios).

**Comment by zippy** [comment]
I've started: https://hackmd.io/MP5F3UhSTp2iPk37Cwa-fw
