### ISSUE TITLE
[REPO] SPIKE: Explore where to place crates with shared-use between HCCore and Networking.

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#35]
- [x] CAS
- [x] EAV (metadata storage vs indexing)
- [x] CAS / EAV implementations
- [x] libsodium
- [x] Logging
- [x] Lib3hProtocol

**Comment by struktured** [comment]
> [ ] CAS

The CAS traits seem portable and abstract enough, as defined in [holochain-rust/core_types/src/cas/*](https://github.com/holochain/holochain-rust/tree/develop/core_types/src/cas). 

Holochain then has a `cas_implementations` crate which provides a file, in memory, and pickle db version. It would be straightforward to do *one* of the following:

 - move the traits _and_ implementations into a `XX` crate, shared by `holochain-rust` and `lib3h`
 - move just the traits into `XX` crate, leave `cas_implementations` in core
   - then we pick one of the databases discussed [here](https://hackmd.io/u3MgMRQDStCY5ra-1UQuFQ?both) as an implementation. Probably one of `rust-kv`, `sled`, or `sqlite3`.

The `XX` crate can either be
 - a new, separate `persistence` crate available from crates.io (w/separate repo?)
 - embedded in existing `lib3h` repo as a module
 - embedded in existing `lib3h` repo  and a _copy/fork_ of the code in `holochain-rust`, with decision of convergence or divergence from it deferred until a more strategic date

**Comment by struktured** [comment]
> [ ] EAV (metadata storage vs indexing)

The EAV, as written currently, is not abstract enough for networking because the attribute is a enum very specific to subconscious metadata of holochain, such as links and crud. Also, the `Value` is typed as json string which may not be our best representation for networking. 

The concept of an EAV however seems an appealing one and without some sort of meta layer on top of the CAS it is not terribly useful. Perhaps we implement an EAV trait more suitable to networking but possibly generalize/merge it in the future with holochain-core (for instance, we could just make the attribute and value generic type parameters with extensible serde requirements). 

Will provide more thoughts and comments on this later- open to any suggestions in the meantime.
